import type { Metadata } from 'next'
import './globals.css'
import { cn } from '@/lib/utils'
import Navbar from '@/components/Navbar'
import { ThemeProvider } from '@/components/ThemeProvider'

export const metadata: Metadata = {
    title: 'Salaried MarketPlace',
    description: 'Generated by create next app',
    icons: [{ rel: 'icon', url: '/wallet.svg' }],
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" className="h-full" suppressHydrationWarning>
            <body className={cn('relative h-full antialiased')}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Navbar />
                    <main className={cn('relative flex flex-col min-h-screen')}>
                        <div className={cn('flex-grow flex-1')}>{children}</div>
                    </main>
                </ThemeProvider>
            </body>
        </html>
    )
}
