import type { Metadata } from 'next'
import './globals.css'
import { cn } from '@/lib/utils'
import Navbar from '@/components/Navbar/Navbar'
import Providers from '@/components/server/Providers'
import { Toaster } from 'sonner'

export const metadata: Metadata = {
    title: 'Salaried MarketPlace',
    description: 'Generated by create next app',
    icons: [{ rel: 'icon', url: '/wallet.svg' }],
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" className="h-full" suppressHydrationWarning>
            <body className={cn('relative h-full antialiased')}>
                <Providers>
                    <Navbar />
                    <main className={cn('relative flex flex-col min-h-max')}>
                        <div className={cn('flex-grow flex-1')}>{children}</div>
                    </main>
                </Providers>
                <Toaster position="top-center" richColors />
            </body>
        </html>
    )
}
